<?php

/**
 * This file is part of the BoxydevBadgeBundle package.
 *
 * (c) Matthieu Mota <matthieu@boxydev.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Boxydev\BadgeBundle\Repository;

/**
 * BadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Matthieu Mota <matthieu@boxydev.com>
 */
class BadgeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithRank($participant, $badge_group, $count)
    {
        return $this->createQueryBuilder('b')
            ->leftJoin('b.ranks', 'u')
            ->where('b.badgeGroup = :badgeGroup')
            ->andWhere('b.count = :count')
            ->andWhere('u.participant = :participant OR u.participant IS NULL')
            ->select('b, u')
            ->setParameters([
                'badgeGroup'  => $badge_group,
                'participant' => $participant,
                'count'       => $count
            ])
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findBadges($participant)
    {
        return $this->createQueryBuilder('b')
            ->join('b.ranks', 'u')
            ->where('u.participant = :participant')
            ->setParameter('participant', $participant)
            ->getQuery()
            ->getResult();
    }
}
